# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.spiel_bereich = QtWidgets.QWidget(self.centralwidget)
        self.spiel_bereich.setObjectName("spiel_bereich")
        self.fang_button = QtWidgets.QPushButton(self.spiel_bereich)
        self.fang_button.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.fang_button.setObjectName("fang_button")
        self.verticalLayout.addWidget(self.spiel_bereich)
        self.status_zeile = QtWidgets.QWidget(self.centralwidget)
        self.status_zeile.setMinimumSize(QtCore.QSize(0, 100))
        self.status_zeile.setObjectName("status_zeile")
        self.widget = QtWidgets.QWidget(self.status_zeile)
        self.widget.setGeometry(QtCore.QRect(30, 70, 144, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treffer_label = QtWidgets.QLabel(self.widget)
        self.treffer_label.setObjectName("treffer_label")
        self.horizontalLayout.addWidget(self.treffer_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.zeit_label = QtWidgets.QLabel(self.widget)
        self.zeit_label.setObjectName("zeit_label")
        self.horizontalLayout.addWidget(self.zeit_label)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 9)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addWidget(self.status_zeile)
        self.verticalLayout.setStretch(0, 9)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fangspiel"))
        self.fang_button.setText(_translate("MainWindow", "Fang mich!"))
        self.treffer_label.setText(_translate("MainWindow", "Treffer: 0"))
        self.zeit_label.setText(_translate("MainWindow", "Zeit: 120"))
